# Generated by Django 4.0.3 on 2022-03-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='url',
            new_name='target_url',
        ),
    ]
